/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface consensusConstants {
  public final static String KTH_CONSENSUS_VERSION = consensusJNI.KTH_CONSENSUS_VERSION_get();
  public final static int KTH_CONSENSUS_MAJOR_VERSION = consensusJNI.KTH_CONSENSUS_MAJOR_VERSION_get();
  public final static int KTH_CONSENSUS_MINOR_VERSION = consensusJNI.KTH_CONSENSUS_MINOR_VERSION_get();
  public final static int KTH_CONSENSUS_PATCH_VERSION = consensusJNI.KTH_CONSENSUS_PATCH_VERSION_get();
}
